import { ShellBridge } from './components/ShellBridge';
import { ContextStatusStrip } from './components/ContextStatusStrip';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ShellBridge />
        {/* paddingBottom reserves space so page content never sits behind the fixed strip below */}
        <div style={{ paddingBottom: '2.25rem' }}>
          {children}
        </div>
        <ContextStatusStrip />
      </body>
    </html>
  )
}